<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-37R1BT8F" ignored="0" name="Parallel" tests="10" failures="7" timestamp="2021-04-09T13:37:07 CAT" time="0.161" errors="0">
  <testcase name="AboutMenu" time="0.04" classname="TestPackage.ListenerParalell"/>
  <testcase name="SourceCodeFalure" time="0.041" classname="TestPackage.ListernerExecute">
    <failure type="java.lang.AssertionError" message="expected [F@!l] but found [fail]">
      <![CDATA[java.lang.AssertionError: expected [F@!l] but found [fail]
at TestPackage.ListernerExecute.SourceCodeFalure(ListernerExecute.java:20)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- SourceCodeFalure -->
  <testcase name="HelpMenu" time="0.003" classname="TestPackage.ListenerParalell">
    <failure type="java.lang.AssertionError" message="expected [F@!l] but found [fail]">
      <![CDATA[java.lang.AssertionError: expected [F@!l] but found [fail]
at TestPackage.ListenerParalell.HelpMenu(ListenerParalell.java:20)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- HelpMenu -->
  <testcase name="Login" time="0.003" classname="TestPackage.ListenerParalell"/>
  <testcase name="Subscriptions" time="0.001" classname="TestPackage.ListenerParalell">
    <failure type="java.lang.AssertionError" message="expected [F@!l] but found [fail]">
      <![CDATA[java.lang.AssertionError: expected [F@!l] but found [fail]
at TestPackage.ListenerParalell.Subscriptions(ListenerParalell.java:34)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- Subscriptions -->
  <testcase name="Users" time="0.025" classname="TestPackage.ListenerParalell">
    <failure type="java.lang.AssertionError" message="expected [F@!l] but found [fail]">
      <![CDATA[java.lang.AssertionError: expected [F@!l] but found [fail]
at TestPackage.ListenerParalell.Users(ListenerParalell.java:41)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- Users -->
  <testcase name="SourceCodeFalureB" time="0.044" classname="TestPackage.ListernerExecute">
    <failure type="java.lang.AssertionError" message="expected [F@!l] but found [fail]">
      <![CDATA[java.lang.AssertionError: expected [F@!l] but found [fail]
at TestPackage.ListernerExecute.SourceCodeFalureB(ListernerExecute.java:27)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- SourceCodeFalureB -->
  <testcase name="SourceCodeFalureC" time="0.002" classname="TestPackage.ListernerExecute">
    <failure type="java.lang.AssertionError" message="expected [F@!l] but found [fail]">
      <![CDATA[java.lang.AssertionError: expected [F@!l] but found [fail]
at TestPackage.ListernerExecute.SourceCodeFalureC(ListernerExecute.java:34)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- SourceCodeFalureC -->
  <testcase name="SourceCodeFalureE" time="0.003" classname="TestPackage.ListernerExecute">
    <failure type="java.lang.AssertionError" message="expected [F@!l] but found [fail]">
      <![CDATA[java.lang.AssertionError: expected [F@!l] but found [fail]
at TestPackage.ListernerExecute.SourceCodeFalureE(ListernerExecute.java:41)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- SourceCodeFalureE -->
  <testcase name="SucessCodeSucess" time="0.003" classname="TestPackage.ListernerExecute"/>
</testsuite> <!-- Parallel -->
